### PR TITLE
Snapshot

### PR DESCRIPTION
**Pull request by ShahJinali**
Please review it.

### CODE REVIEW

**Comment by AnkitVig** [comment]
The file testMain.c doesn't follow all the coding conventions.
     - The braces for if statement are not correct 
     - comments added are not in the proper format

**Comment by AnkitVig** [comment]
The file validation.h in include folder doesn't follow all the coding conventions for the comments.

**Comment by ShahJinali** [comment]
> The file testMain.c doesn't follow all the coding conventions.
> - The braces for if statement are not correct
> - comments added are not in the proper format

testMain.c is not complete yet.We are still working on it.

**Comment by ShahJinali** [comment]
> The file validation.h in include folder doesn't follow all the coding conventions for the comments.

Thanks , we forget to document this file.

**Comment by ShahJinali** [comment]
> > The file validation.h in include folder doesn't follow all the coding conventions for the comments.
> 
> Thanks , we forget to document this file.

Have a look at the updated file of validate_sensor.h and validate_sensor.c

**Comment by rushabh1410** [comment]
The file testMain.c is going to complete by tonight.

**Comment by ShahJinali** [comment]
testMain.c is  updated in another branch called test.

**Comment by AnkitVig** [comment]
I am merging the branch. with no conflicts. Its just a suggestion to provide documentation for other Operating system.

**Review by shreyataneja — COMMENTED** [review]
Looks good.

**Pull request closed without merging**
